/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DatePickerResponsive: typeof import('./src/components/DatePickerResponsive.vue')['default']
    DateRangePicker: typeof import('./src/components/DateRangePicker.vue')['default']
    DateRangePickerModal: typeof import('./src/components/modals/DateRangePickerModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepOne: typeof import('./src/components/StepOne.vue')['default']
  }
}
