/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionToast: typeof import('./src/components/toasts/ActionToast.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DatePickerResponsive: typeof import('./src/components/DatePickerResponsive.vue')['default']
    DateRangePicker: typeof import('./src/components/DateRangePicker.vue')['default']
    DateRangePickerModal: typeof import('./src/components/modals/DateRangePickerModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PackageInfoBox: typeof import('./src/components/PackageInfoBox.vue')['default']
    ParticipantAccordion: typeof import('./src/components/ParticipantAccordion.vue')['default']
    PopupSmall: typeof import('./src/components/modals/PopupSmall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedParticipantClasses: typeof import('./src/components/SelectedParticipantClasses.vue')['default']
    StepOne: typeof import('./src/components/StepOne.vue')['default']
    StepThree: typeof import('./src/components/StepThree.vue')['default']
    StepTwo: typeof import('./src/components/StepTwo.vue')['default']
    Toast: typeof import('./src/components/toasts/Toast.vue')['default']
  }
}
